//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_00.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multas
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int PrestamoID { get; set; }
        public decimal Monto { get; set; }
        public string Estado { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
