//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_00.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamos()
        {
            this.Multas = new HashSet<Multas>();
            this.PrestamosPendientes = new HashSet<PrestamosPendientes>();
        }
    
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int LibroID { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public System.DateTime FechaCompromiso { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Estado { get; set; }
    
        public virtual Libros Libros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Multas> Multas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestamosPendientes> PrestamosPendientes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
