//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_00.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoBibliotecaBetaEntities : DbContext
    {
        public ProyectoBibliotecaBetaEntities()
            : base("name=ProyectoBibliotecaBetaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administradores> Administradores { get; set; }
        public virtual DbSet<Autores> Autores { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<HistorialPrestamos> HistorialPrestamos { get; set; }
        public virtual DbSet<Libros> Libros { get; set; }
        public virtual DbSet<Multas> Multas { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
        public virtual DbSet<PrestamosPendientes> PrestamosPendientes { get; set; }
        public virtual DbSet<Solicitudes> Solicitudes { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Vista_PrestamosActivosPorUsuario> Vista_PrestamosActivosPorUsuario { get; set; }
        public virtual DbSet<Vista_PrestamosPorUsuario> Vista_PrestamosPorUsuario { get; set; }
    }
}
